//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public Game()
        {
            this.Drawings = new HashSet<Drawing>();
            this.Game_Days = new HashSet<Game_Days>();
            this.Games_States = new HashSet<Games_States>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Game_Balls { get; set; }
        public string Bottom_Game_Ball { get; set; }
        public string Top_Game_Ball { get; set; }
        public string Bonus_Balls { get; set; }
        public string Bottom_Bonus_Ball { get; set; }
        public string Top_Bonus_Ball { get; set; }
        public string Site_Url { get; set; }
        public string Permutations { get; set; }
        public string Drawing_Time { get; set; }
    
        public virtual ICollection<Drawing> Drawings { get; set; }
        public virtual ICollection<Game_Days> Game_Days { get; set; }
        public virtual ICollection<Games_States> Games_States { get; set; }
    }
}
