//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LottoContinuumEntities : DbContext
    {
        public LottoContinuumEntities()
            : base("name=LottoContinuumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Drawing> Drawings { get; set; }
        public DbSet<Game_Days> Game_Days { get; set; }
        public DbSet<Game> Games { get; set; }
        public DbSet<Games_States> Games_States { get; set; }
        public DbSet<State> States { get; set; }
    }
}
